[INFO] Central web server started at [2025-04-05 18:48:48.181]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-05 18:48:48.636]
[INFO] Made request to synchronize dictionary at [2025-04-05 18:48:50.823]
[INFO] Created dictionary directory at [2025-04-05 18:48:50.839]
[INFO] Successfully saved new dictionary at [2025-04-05 18:48:50.847]
[INFO] Made request to crack password using dictionary method at [2025-04-05 18:48:50.868]
[INFO] Final cracking time with dictionary method was: 01:34:10. Cracking was successfull. at [2025-04-05 18:48:50.872]
[INFO] Central web server started at [2025-04-05 18:51:19.425]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-05 18:51:19.949]
[INFO] Made request to synchronize dictionary at [2025-04-05 18:51:30.638]
[INFO] Successfully saved new dictionary with size: 12 bytes at [2025-04-05 18:51:30.676]
[INFO] Made request to crack password using dictionary method at [2025-04-05 18:51:30.697]
[INFO] Final cracking time with dictionary method was: 01:34:10. Cracking was successfull. at [2025-04-05 18:51:30.702]
[INFO] Central web server started at [2025-04-05 18:54:32.457]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-05 18:54:32.968]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.10 at [2025-04-05 18:55:06.393]
[INFO] No dictionary found on server 192.168.0.10, starting synchronization at [2025-04-05 18:55:06.494]
[INFO] Successfully synchronized dictionary with server 192.168.0.10 at [2025-04-05 18:55:06.558]
[INFO] Successfully connected to calculating server 192.168.0.10 at [2025-04-05 18:55:06.570]
[INFO] Calculating server with IP address: 192.168.0.10 successfully connected to the central server at [2025-04-05 18:55:06.574]
[INFO] Central web server started at [2025-04-05 18:55:51.016]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-05 18:55:51.453]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.10 at [2025-04-05 18:56:02.931]
[INFO] Dictionary already exists on server 192.168.0.10 at path: /App/dictionary/dictionary-E21B6C5BAE3D9C39-2025-04-05.txt at [2025-04-05 18:56:03.034]
[INFO] Successfully connected to calculating server 192.168.0.10 at [2025-04-05 18:56:03.038]
[INFO] Calculating server with IP address: 192.168.0.10 successfully connected to the central server at [2025-04-05 18:56:03.052]
[INFO] Central web server started at [2025-04-05 18:56:49.486]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-05 18:56:49.960]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.10 at [2025-04-05 18:57:01.230]
[INFO] Created dictionary directory at [2025-04-05 18:57:01.243]
[ERROR] No files found in directory path while trying to getting current dictionary hash at [2025-04-05 18:57:01.252]
[ERROR] Error while retrieving current dictionary hash: No files found in directory path. at [2025-04-05 18:57:01.257]
[INFO] No dictionary found on server 192.168.0.10, starting synchronization at [2025-04-05 18:57:01.342]
[ERROR] No files found in directory path while trying to getting current dictionary hash at [2025-04-05 18:57:01.348]
[ERROR] Failed to connect with calculating server 192.168.0.10 for reason: No files found in directory path. at [2025-04-05 18:57:01.358]
[ERROR] Cannot connect to calculating server due to: No files found in directory path. at [2025-04-05 18:57:01.364]
[INFO] Central web server started at [2025-04-05 19:04:43.632]
[ERROR] An error occurred: Database test connection exception Resource temporarily unavailable at [2025-04-05 19:04:53.763]
[INFO] Central web server started at [2025-04-05 19:06:25.344]
[INFO] Central web server started at [2025-04-05 19:06:29.997]
[ERROR] An error occurred: Database test connection exception Resource temporarily unavailable at [2025-04-05 19:06:40.123]
[INFO] Central web server started at [2025-04-05 19:08:32.785]
[ERROR] An error occurred: Database test connection exception Resource temporarily unavailable at [2025-04-05 19:08:42.895]
[INFO] Central web server started at [2025-04-05 19:11:32.692]
[ERROR] An error occurred: Database test connection exception Resource temporarily unavailable at [2025-04-05 19:11:42.823]
[INFO] Central web server started at [2025-04-05 19:15:20.857]
[ERROR] An error occurred: Database test connection exception Resource temporarily unavailable at [2025-04-05 19:15:30.972]
[INFO] Central web server started at [2025-04-05 19:16:19.848]
[ERROR] An error occurred: Database test connection exception Resource temporarily unavailable at [2025-04-05 19:16:29.973]
[INFO] Central web server started at [2025-04-05 19:19:39.504]
[ERROR] An error occurred: Database test connection exception Resource temporarily unavailable at [2025-04-05 19:19:49.642]
[INFO] Central web server started at [2025-04-05 19:19:52.253]
[ERROR] An error occurred: Database test connection exception Resource temporarily unavailable at [2025-04-05 19:20:02.373]
[INFO] Central web server started at [2025-04-05 19:21:04.610]
[ERROR] An error occurred: Database test connection exception Resource temporarily unavailable at [2025-04-05 19:21:14.742]
[INFO] Central web server started at [2025-04-05 19:23:36.900]
[ERROR] An error occurred: Database test connection exception Resource temporarily unavailable at [2025-04-05 19:23:47.022]
[INFO] Central web server started at [2025-04-05 19:24:57.774]
[ERROR] An error occurred: Database test connection exception 28P01: password authentication failed for user "postgres_db_username" at [2025-04-05 19:24:57.913]
[INFO] Central web server started at [2025-04-05 19:26:43.307]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-05 19:26:43.633]
[INFO] Central web server started at [2025-04-12 18:34:51.390]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 18:34:51.756]
[INFO] Central web server started at [2025-04-12 18:36:24.668]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 18:36:24.998]
[INFO] Central web server started at [2025-04-12 18:36:30.371]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 18:36:30.707]
[INFO] Central web server started at [2025-04-12 18:56:45.368]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 18:56:45.670]
[INFO] Central web server started at [2025-04-12 19:00:17.235]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 19:00:17.519]
[INFO] Made request to crack password using brute force method at [2025-04-12 19:00:22.881]
[INFO] Central web server started at [2025-04-12 19:02:00.949]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 19:02:01.255]
[INFO] Central web server started at [2025-04-12 19:07:04.498]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 19:07:04.814]
[INFO] Made request to crack password using brute force method at [2025-04-12 19:07:07.347]
[INFO]  at [2025-04-12 19:07:07.349]
[INFO] Made request to crack password using brute force method at [2025-04-12 19:07:17.922]
[INFO]  at [2025-04-12 19:07:17.924]
[INFO] Central web server started at [2025-04-12 19:07:48.263]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 19:07:48.556]
[INFO] Made request to crack password using brute force method at [2025-04-12 19:07:50.964]
[INFO]  at [2025-04-12 19:07:50.965]
[INFO] Test message. at [2025-04-12 19:07:50.967]
[INFO] Made request to crack password using brute force method at [2025-04-12 19:07:52.220]
[INFO]  at [2025-04-12 19:07:52.221]
[INFO] Test message. at [2025-04-12 19:07:52.223]
[INFO] Central web server started at [2025-04-12 19:08:21.397]
[INFO] Made request to crack password using brute force method at [2025-04-12 19:08:21.722]
2]
[INFO] Test message. at [2025-04-12 19:08:21.723]
[INFO] Made request to crack password using brute force method at [2025-04-12 19:08:22.346]
[INFO] Test message. at [2025-04-12 19:08:22.348]
[INFO] Made request to crack password using brute force method at [2025-04-12 19:08:23.028]
[INFO] Test message. at [2025-04-12 19:08:23.030]
[INFO] Central web server started at [2025-04-12 19:08:37.513]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 19:08:37.808]
[INFO] Made request to crack password using brute force method at [2025-04-12 19:09:46.734]
[INFO] {
    "userLogin": "choroszcz",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 19:09:46.736]
[INFO] Central web server started at [2025-04-12 19:09:56.639]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 19:09:56.942]
[INFO] Central web server started at [2025-04-12 19:14:15.033]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 19:14:15.367]
[INFO] Central web server started at [2025-04-12 19:17:00.309]
[ERROR] An error occurred: Database test connection exception Exception while connecting at [2025-04-12 19:17:15.408]
[INFO] Central web server started at [2025-04-12 19:19:58.240]
[ERROR] An error occurred: Database test connection exception Exception while connecting at [2025-04-12 19:20:00.561]
[INFO] Central web server started at [2025-04-12 19:21:27.336]
[ERROR] An error occurred: Database test connection exception Exception while connecting at [2025-04-12 19:21:29.737]
[INFO] Central web server started at [2025-04-12 19:21:59.174]
[ERROR] An error occurred: Database test connection exception Exception while connecting at [2025-04-12 19:22:01.465]
[INFO] Central web server started at [2025-04-12 19:23:39.523]
[ERROR] An error occurred: Database test connection exception Exception while connecting at [2025-04-12 19:23:41.814]
[INFO] Central web server started at [2025-04-12 19:24:55.770]
[ERROR] An error occurred: Database test connection exception Exception while connecting at [2025-04-12 19:24:58.057]
[INFO] Central web server started at [2025-04-12 19:25:22.526]
[ERROR] An error occurred: Database test connection exception Exception while connecting at [2025-04-12 19:25:24.902]
[INFO] Central web server started at [2025-04-12 19:26:06.456]
[ERROR] An error occurred: Database test connection exception Exception while connecting at [2025-04-12 19:26:08.824]
[INFO] Central web server started at [2025-04-12 19:27:28.914]
[ERROR] An error occurred: Database test connection exception: Exception while connecting at [2025-04-12 19:27:31.214]
[ERROR] An error occurred: Stack Trace:    at Npgsql.NpgsqlConnector.ConnectAsync(NpgsqlTimeout timeout, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnector.RawOpen(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.ConnectorPool.OpenNewConnector(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.ConnectorPool.<>c__DisplayClass38_0.<<Rent>g__RentAsync|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Npgsql.NpgsqlConnection.<>c__DisplayClass41_0.<<Open>g__OpenAsync|0>d.MoveNext()
--- End of stack trace from previous location ---
   at backend___central.Startup.TestConnectionWithDatabase() in /App/Startup.cs:line 111 at [2025-04-12 19:27:31.228]
[INFO] Central web server started at [2025-04-12 19:30:34.771]
[ERROR] An error occurred: Database test connection exception: Exception while connecting at [2025-04-12 19:30:37.035]
[ERROR] An error occurred: Stack Trace:    at Npgsql.NpgsqlConnector.ConnectAsync(NpgsqlTimeout timeout, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnector.RawOpen(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.ConnectorPool.OpenNewConnector(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.ConnectorPool.<>c__DisplayClass38_0.<<Rent>g__RentAsync|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Npgsql.NpgsqlConnection.<>c__DisplayClass41_0.<<Open>g__OpenAsync|0>d.MoveNext()
--- End of stack trace from previous location ---
   at backend___central.Startup.TestConnectionWithDatabase() in /App/Startup.cs:line 111 at [2025-04-12 19:30:37.049]
[INFO] Central web server started at [2025-04-12 19:34:49.136]
[ERROR] An error occurred: Database test connection exception: Exception while connecting at [2025-04-12 19:34:51.455]
[ERROR] An error occurred: Stack Trace:    at Npgsql.NpgsqlConnector.ConnectAsync(NpgsqlTimeout timeout, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnector.RawOpen(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.ConnectorPool.OpenNewConnector(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.ConnectorPool.<>c__DisplayClass38_0.<<Rent>g__RentAsync|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Npgsql.NpgsqlConnection.<>c__DisplayClass41_0.<<Open>g__OpenAsync|0>d.MoveNext()
--- End of stack trace from previous location ---
   at backend___central.Startup.TestConnectionWithDatabase() in /App/Startup.cs:line 111 at [2025-04-12 19:34:51.468]
[INFO] Central web server started at [2025-04-12 19:42:52.356]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 19:42:53.240]
[INFO] Central web server started at [2025-04-12 19:43:38.589]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 19:43:39.091]
[INFO] Central web server started at [2025-04-12 20:21:43.868]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 20:21:44.449]
[INFO] Central web server started at [2025-04-12 20:22:05.776]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 20:22:06.272]
[INFO] Central web server started at [2025-04-12 20:23:15.403]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 20:23:15.869]
[INFO] Central web server started at [2025-04-12 20:23:23.055]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 20:23:23.528]
[INFO] Made request to crack password using brute force method at [2025-04-12 20:23:25.308]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 20:23:25.310]
[INFO] Central web server started at [2025-04-12 20:24:32.956]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 20:24:33.432]
[INFO] Made request to crack password using brute force method at [2025-04-12 20:24:35.310]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 20:24:35.312]
[INFO] Central web server started at [2025-04-12 20:25:04.683]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 20:25:05.186]
[INFO] Made request to crack password using brute force method at [2025-04-12 20:25:06.290]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 20:25:06.292]
[ERROR] Cannot connect to calculating server due to: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') at [2025-04-12 20:25:06.295]
[INFO] Central web server started at [2025-04-12 20:26:08.459]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 20:26:08.971]
[INFO] Made request to crack password using brute force method at [2025-04-12 20:26:13.831]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 20:26:13.833]
[INFO] Made request to crack password using brute force method at [2025-04-12 20:27:17.262]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 20:27:17.263]
[INFO] Made request to crack password using brute force method at [2025-04-12 20:27:18.227]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 20:27:18.228]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-12 20:28:49.559]
[ERROR] No files found in directory path while trying to getting current dictionary hash at [2025-04-12 20:28:49.563]
[ERROR] Error while retrieving current dictionary hash: No files found in directory path. at [2025-04-12 20:28:49.564]
[INFO] No dictionary found on server 192.168.0.52, starting synchronization at [2025-04-12 20:28:49.615]
[ERROR] No files found in directory path while trying to getting current dictionary hash at [2025-04-12 20:28:49.618]
[ERROR] Failed to connect with calculating server 192.168.0.52 for reason: No files found in directory path. at [2025-04-12 20:28:49.620]
[ERROR] Cannot connect to calculating server due to: No files found in directory path. at [2025-04-12 20:28:49.621]
[INFO] Made request to synchronize dictionary at [2025-04-12 20:31:34.820]
[INFO] Successfully saved new dictionary with size: 434 bytes at [2025-04-12 20:31:34.830]
[INFO] Made request to crack password using dictionary method at [2025-04-12 20:31:34.835]
[INFO] Final cracking time with dictionary method was: 01:34:10. Cracking was successfull. at [2025-04-12 20:31:34.836]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-12 20:31:48.392]
[INFO] No dictionary found on server 192.168.0.52, starting synchronization at [2025-04-12 20:31:48.440]
[INFO] Successfully synchronized dictionary with server 192.168.0.52 at [2025-04-12 20:31:48.483]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 20:31:48.485]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-12 20:31:48.486]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-12 20:33:14.751]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 20:33:14.797]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 20:33:14.798]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-12 20:33:14.799]
[INFO] Central web server started at [2025-04-12 20:33:41.225]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 20:33:41.690]
[INFO] Made request to crack password using brute force method at [2025-04-12 20:33:42.308]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 20:33:42.310]
[INFO] Made request to crack password using brute force method at [2025-04-12 20:34:36.810]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 20:34:36.811]
[INFO] Made request to crack password using brute force method at [2025-04-12 20:34:37.995]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 20:34:37.996]
[INFO] Central web server started at [2025-04-12 20:34:47.248]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 20:34:47.758]
[INFO] Made request to crack password using brute force method at [2025-04-12 20:34:48.297]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 20:34:48.299]
[INFO] Made request to crack password using brute force method at [2025-04-12 20:34:49.177]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 20:34:49.178]
[INFO] Made request to crack password using brute force method at [2025-04-12 20:34:50.003]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 20:34:50.004]
[INFO] Central web server started at [2025-04-12 20:35:42.551]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 20:35:43.020]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-12 20:36:17.644]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 20:36:17.702]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 20:36:17.703]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-12 20:36:17.708]
[INFO] Made request to crack password using brute force method at [2025-04-12 20:36:26.217]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 20:36:26.219]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 20:36:26.229]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 20:36:26.230]
[INFO] Made request to crack password using brute force method at [2025-04-12 20:36:45.511]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 20:36:45.512]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 20:36:45.522]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 20:36:45.523]
[INFO] Made request to crack password using brute force method at [2025-04-12 20:36:46.792]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 20:36:46.793]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 20:36:46.801]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 20:36:46.802]
[INFO] Central web server started at [2025-04-12 20:36:53.481]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 20:36:53.977]
[INFO] Made request to crack password using brute force method at [2025-04-12 20:36:54.065]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 20:36:54.067]
[INFO] Made request to crack password using brute force method at [2025-04-12 20:36:55.855]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 20:36:55.856]
[INFO] Central web server started at [2025-04-12 20:37:00.601]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 20:37:01.117]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-12 20:37:06.916]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 20:37:06.975]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 20:37:06.976]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-12 20:37:06.981]
[INFO] Made request to crack password using brute force method at [2025-04-12 20:37:10.458]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 20:37:10.460]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 20:37:10.471]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 20:37:10.472]
[INFO] Made request to crack password using brute force method at [2025-04-12 20:37:11.531]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 20:37:11.533]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 20:37:11.543]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 20:37:11.544]
[INFO] Made request to crack password using brute force method at [2025-04-12 20:37:22.158]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 20:37:22.160]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 20:37:22.171]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 20:37:22.172]
[INFO] Central web server started at [2025-04-12 20:37:45.544]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 20:37:46.122]
[INFO] Central web server started at [2025-04-12 20:53:51.105]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 20:53:51.742]
[INFO] Central web server started at [2025-04-12 20:54:00.995]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 20:54:01.504]
[INFO] Central web server started at [2025-04-12 21:00:09.788]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 21:00:10.361]
[INFO] Made request to crack password using brute force method at [2025-04-12 21:00:18.255]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 21:00:18.258]
[INFO] Central web server started at [2025-04-12 21:01:51.981]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 21:01:52.487]
[INFO] Central web server started at [2025-04-12 21:03:40.681]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 21:03:41.132]
[INFO] Made request to crack password using brute force method at [2025-04-12 21:04:11.646]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 21:04:11.649]
[INFO] Central web server started at [2025-04-12 21:04:32.210]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 21:04:32.727]
[INFO] Made request to crack password using brute force method at [2025-04-12 21:04:34.670]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 21:04:34.672]
[INFO] Central web server started at [2025-04-12 21:05:18.399]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 21:05:18.945]
[INFO] Central web server started at [2025-04-12 21:15:39.917]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 21:15:40.397]
[INFO] Made request to crack password using brute force method at [2025-04-12 21:17:10.728]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 21:17:10.730]
[INFO] Central web server started at [2025-04-12 21:18:06.361]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 21:18:06.981]
[INFO] Central web server started at [2025-04-12 21:18:23.666]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 21:18:24.214]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-12 21:19:45.607]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 21:19:45.668]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 21:19:45.669]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-12 21:19:45.675]
[INFO] Made request to crack password using brute force method at [2025-04-12 21:19:49.949]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 21:19:49.950]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 21:19:49.962]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 21:19:49.963]
[ERROR] Cannot connect to calculating server due to: One or more errors occurred. (Connection refused (192.168.0.52:80)) at [2025-04-12 21:19:51.994]
[INFO] Central web server started at [2025-04-12 21:20:58.998]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 21:20:59.506]
[INFO] Made request to crack password using brute force method at [2025-04-12 21:21:05.171]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 21:21:05.173]
[INFO] Central web server started at [2025-04-12 21:21:36.753]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 21:21:37.322]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-12 21:21:41.058]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 21:21:41.122]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 21:21:41.123]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-12 21:21:41.129]
[INFO] Made request to crack password using brute force method at [2025-04-12 21:22:20.207]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 21:22:20.208]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 21:22:20.217]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 21:22:20.218]
[ERROR] Cannot connect to calculating server due to: One or more errors occurred. (Connection refused (192.168.0.52:80)) at [2025-04-12 21:22:22.264]
[INFO] Central web server started at [2025-04-12 21:23:32.608]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 21:23:33.122]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-12 21:23:34.084]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 21:23:34.145]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 21:23:34.146]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-12 21:23:34.152]
[INFO] Made request to crack password using brute force method at [2025-04-12 21:23:53.360]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 21:23:53.361]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 21:23:53.371]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 21:23:53.373]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-12 21:26:38.555]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 21:26:38.602]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 21:26:38.603]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-12 21:26:38.604]
[INFO] Made request to crack password using brute force method at [2025-04-12 21:26:52.356]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 21:26:52.358]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 21:26:52.368]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 21:26:52.369]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 21:26:52.380]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 21:26:52.381]
[INFO] Made request to crack password using brute force method at [2025-04-12 21:26:55.128]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 21:26:55.130]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 21:26:55.139]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 21:26:55.140]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 21:26:55.150]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 21:26:55.151]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-12 21:27:11.204]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 21:27:11.250]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 21:27:11.251]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-12 21:27:11.252]
[INFO] Made request to crack password using brute force method at [2025-04-12 21:27:13.172]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 21:27:13.173]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 21:27:13.183]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 21:27:13.185]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 21:27:13.197]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 21:27:13.198]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 21:27:13.210]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 21:27:13.211]
[INFO] Made request to crack password using brute force method at [2025-04-12 21:27:18.340]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 21:27:18.342]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 21:27:18.352]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 21:27:18.353]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 21:27:18.364]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 21:27:18.365]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 21:27:18.375]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 21:27:18.376]
[INFO] Central web server started at [2025-04-12 21:28:30.165]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 21:28:30.735]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-12 21:29:17.565]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 21:29:17.628]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 21:29:17.630]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-12 21:29:17.635]
[INFO] Made request to crack password using brute force method at [2025-04-12 21:29:27.298]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 21:29:27.299]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 21:29:27.311]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 21:29:27.312]
[INFO] Made request to crack password using brute force method at [2025-04-12 21:29:35.894]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 21:29:35.895]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 21:29:35.905]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 21:29:35.906]
[INFO] Made request to crack password using brute force method at [2025-04-12 21:30:06.830]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 21:30:06.832]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 21:30:06.840]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 21:30:06.841]
[INFO] Central web server started at [2025-04-12 21:30:40.802]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 21:30:41.308]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-12 21:30:48.975]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 21:30:49.035]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 21:30:49.037]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-12 21:30:49.043]
[INFO] Made request to crack password using brute force method at [2025-04-12 21:30:59.316]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 21:30:59.318]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 21:30:59.330]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 21:30:59.331]
[INFO] Central web server started at [2025-04-12 21:31:35.943]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 21:31:36.442]
[INFO] Central web server started at [2025-04-12 21:31:42.407]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 21:31:42.888]
[INFO] Made request to crack password using brute force method at [2025-04-12 21:31:48.442]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 21:31:48.444]
[INFO] Central web server started at [2025-04-12 21:32:19.168]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 21:32:19.664]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-12 21:32:31.882]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 21:32:31.942]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 21:32:31.943]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-12 21:32:31.949]
[INFO] Made request to crack password using brute force method at [2025-04-12 21:33:01.736]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 21:33:01.738]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 21:33:01.750]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 21:33:01.751]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-12 21:34:10.581]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 21:34:10.629]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 21:34:10.630]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-12 21:34:10.632]
[INFO] Central web server started at [2025-04-12 21:34:35.896]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 21:34:36.392]
[INFO] Central web server started at [2025-04-12 21:36:22.739]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 21:36:23.224]
[INFO] Central web server started at [2025-04-12 21:37:12.245]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 21:37:12.895]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-12 21:37:14.128]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 21:37:14.188]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 21:37:14.189]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-12 21:37:14.195]
[INFO] Made request to crack password using brute force method at [2025-04-12 21:37:18.610]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 21:37:18.612]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 21:37:18.623]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 21:37:18.624]
[INFO] Central web server started at [2025-04-12 21:38:32.713]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 21:38:33.264]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-12 21:44:39.386]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 21:44:39.445]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 21:44:39.446]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-12 21:44:39.448]
[INFO] Central web server started at [2025-04-12 21:45:02.115]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 21:45:02.595]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-12 21:45:29.112]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 21:45:29.172]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 21:45:29.173]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-12 21:45:29.179]
[INFO] Made request to crack password using brute force method at [2025-04-12 21:45:33.411]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 21:45:33.413]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 21:45:33.426]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 21:45:33.427]
[INFO] Central web server started at [2025-04-12 21:46:22.980]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 21:46:23.529]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-12 21:46:32.455]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 21:46:32.515]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 21:46:32.516]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-12 21:46:32.522]
[INFO] Made request to crack password using brute force method at [2025-04-12 21:46:37.155]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 21:46:37.156]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 21:46:37.167]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 21:46:37.168]
[INFO] Central web server started at [2025-04-12 21:53:44.448]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 21:53:44.968]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-12 21:53:55.130]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 21:53:55.195]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 21:53:55.197]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-12 21:53:55.202]
[INFO] Made request to crack password using brute force method at [2025-04-12 21:53:58.545]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 21:53:58.546]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 21:53:58.567]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 21:53:58.569]
[INFO] Central web server started at [2025-04-12 21:55:06.004]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 21:55:06.503]
[INFO] Central web server started at [2025-04-12 21:56:04.362]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 21:56:04.917]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-12 21:56:57.043]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 21:56:57.104]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 21:56:57.106]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-12 21:56:57.112]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-12 21:57:02.629]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 21:57:02.681]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 21:57:02.683]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-12 21:57:02.684]
[INFO] Central web server started at [2025-04-12 22:02:41.362]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 22:02:41.844]
[INFO] Central web server started at [2025-04-12 22:03:47.496]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 22:03:47.927]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-12 22:03:53.314]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 22:03:53.375]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 22:03:53.376]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-12 22:03:53.382]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-12 22:04:12.392]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 22:04:12.438]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 22:04:12.439]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-12 22:04:12.440]
[INFO] Made request to crack password using brute force method at [2025-04-12 22:04:30.215]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 22:04:30.217]
[ERROR] Cannot connect to calculating server due to: Unable to cast object of type 'System.Text.Json.JsonElement' to type 'System.IConvertible'. at [2025-04-12 22:04:30.222]
[INFO] Central web server started at [2025-04-12 22:06:23.305]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 22:06:23.841]
[INFO] Made request to crack password using brute force method at [2025-04-12 22:06:29.327]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 22:06:29.330]
[INFO] Made request to crack password using brute force method at [2025-04-12 22:06:43.567]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 22:06:43.568]
[INFO] Central web server started at [2025-04-12 22:07:18.115]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 22:07:18.609]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-12 22:07:35.690]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 22:07:35.749]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 22:07:35.750]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-12 22:07:35.755]
[INFO] Made request to crack password using brute force method at [2025-04-12 22:07:58.472]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 22:07:58.473]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 22:07:58.484]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 22:07:58.485]
[INFO] Central web server started at [2025-04-12 22:09:57.221]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 22:09:57.721]
[INFO] Central web server started at [2025-04-12 22:10:01.286]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 22:10:01.761]
[INFO] Central web server started at [2025-04-12 22:10:06.054]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 22:10:06.572]
[INFO] Central web server started at [2025-04-12 22:11:55.707]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 22:11:56.201]
[INFO] Central web server started at [2025-04-12 22:12:39.299]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 22:12:39.781]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-12 22:13:00.080]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 22:13:00.142]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 22:13:00.143]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-12 22:13:00.149]
[INFO] Central web server started at [2025-04-12 22:13:46.614]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 22:13:47.153]
[INFO] Central web server started at [2025-04-12 22:13:56.184]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 22:13:56.668]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-12 22:14:12.665]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 22:14:12.727]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 22:14:12.728]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-12 22:14:12.735]
[INFO] Made request to crack password using brute force method at [2025-04-12 22:14:21.726]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 22:14:21.728]
[ERROR] Cannot connect to calculating server due to: Unable to cast object of type 'System.Text.Json.JsonElement' to type 'System.IConvertible'. at [2025-04-12 22:14:21.733]
[INFO] Central web server started at [2025-04-12 22:14:33.266]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 22:14:33.743]
[INFO] Made request to crack password using brute force method at [2025-04-12 22:14:36.048]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 22:14:36.050]
[INFO] Made request to crack password using brute force method at [2025-04-12 22:14:39.140]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 22:14:39.142]
[INFO] Central web server started at [2025-04-12 22:14:54.624]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 22:14:55.155]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-12 22:15:01.845]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 22:15:01.906]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 22:15:01.907]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-12 22:15:01.913]
[INFO] Made request to crack password using brute force method at [2025-04-12 22:15:12.741]
[INFO] {
    "userLogin": "test123",
    "hostsCount": 12,
    "passwordLength": 12
} at [2025-04-12 22:15:12.742]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 22:15:12.755]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 22:15:12.756]
[INFO] Central web server started at [2025-04-12 22:25:39.491]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-12 22:25:39.990]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-12 22:25:48.427]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-12 22:25:48.490]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-12 22:25:48.491]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-12 22:25:48.497]
[INFO] Central web server started at [2025-04-14 19:33:44.011]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-14 19:33:44.611]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-14 19:34:34.375]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 19:34:34.436]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 19:34:34.437]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-14 19:34:34.443]
[INFO] Made request to crack password using brute force method at [2025-04-14 19:37:25.832]
[INFO] {"username":"user1","passwordLength":8} at [2025-04-14 19:37:25.833]
[INFO] Made request to crack password using brute force method at [2025-04-14 19:37:34.586]
[INFO] {"username":"user1","passwordLength":8} at [2025-04-14 19:37:34.587]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-14 19:37:57.288]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 19:37:57.334]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 19:37:57.336]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-14 19:37:57.337]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-14 19:38:01.152]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 19:38:01.198]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 19:38:01.200]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-14 19:38:01.201]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-14 19:38:08.034]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 19:38:08.081]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 19:38:08.082]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-14 19:38:08.083]
[INFO] Central web server started at [2025-04-14 19:38:13.416]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-14 19:38:14.006]
[INFO] Made request to crack password using brute force method at [2025-04-14 19:38:20.515]
[INFO] {"username":"user1","passwordLength":8} at [2025-04-14 19:38:20.518]
[INFO] Central web server started at [2025-04-14 19:40:32.052]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-14 19:40:32.560]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-14 19:40:34.018]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 19:40:34.083]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 19:40:34.084]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-14 19:40:34.090]
[INFO] Central web server started at [2025-04-14 19:43:47.981]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-14 19:43:48.481]
[INFO] Central web server started at [2025-04-14 19:47:49.195]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-14 19:47:49.740]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-14 19:47:58.631]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 19:47:58.691]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 19:47:58.692]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-14 19:47:58.698]
[INFO] Made request to crack password using brute force method at [2025-04-14 19:48:25.148]
[INFO] {"username":"user1","passwordLength":8} at [2025-04-14 19:48:25.150]
[INFO] Central web server started at [2025-04-14 19:49:37.999]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-14 19:49:38.502]
[INFO] Made request to crack password using brute force method at [2025-04-14 19:52:07.762]
[INFO] {"username":"user1","passwordLength":8} at [2025-04-14 19:52:07.764]
[INFO] Central web server started at [2025-04-14 19:52:30.667]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-14 19:52:31.082]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-14 19:52:34.273]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 19:52:34.334]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 19:52:34.336]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-14 19:52:34.341]
[INFO] Made request to crack password using brute force method at [2025-04-14 19:52:52.511]
[INFO] {"userLogin":"user1","passwordLength":8} at [2025-04-14 19:52:52.513]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 19:52:52.524]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 19:52:52.526]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-14 19:54:57.101]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 19:54:57.148]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 19:54:57.149]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-14 19:54:57.151]
[INFO] Made request to crack password using brute force method at [2025-04-14 19:54:59.118]
[INFO] {"userLogin":"user1","passwordLength":8} at [2025-04-14 19:54:59.119]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 19:54:59.130]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 19:54:59.132]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 19:54:59.156]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 19:54:59.158]
[INFO] Made request to crack password using brute force method at [2025-04-14 19:55:53.059]
[INFO] {"userLogin":"user1","passwordLength":8} at [2025-04-14 19:55:53.060]
[ERROR] Failed to connect with calculating server 192.168.0.52 for reason: An error occurred while sending the request. at [2025-04-14 19:55:53.067]
[ERROR] Cannot connect to calculating server due to: An error occurred while sending the request. at [2025-04-14 19:55:53.069]
[INFO] Made request to crack password using brute force method at [2025-04-14 19:55:54.032]
[INFO] {"userLogin":"user1","passwordLength":8} at [2025-04-14 19:55:54.033]
[ERROR] Failed to connect with calculating server 192.168.0.52 for reason: An error occurred while sending the request. at [2025-04-14 19:55:54.038]
[ERROR] Cannot connect to calculating server due to: An error occurred while sending the request. at [2025-04-14 19:55:54.040]
[INFO] Made request to crack password using brute force method at [2025-04-14 19:56:01.251]
[INFO] {"userLogin":"user1","passwordLength":7} at [2025-04-14 19:56:01.252]
[ERROR] Failed to connect with calculating server 192.168.0.52 for reason: An error occurred while sending the request. at [2025-04-14 19:56:01.265]
[ERROR] Cannot connect to calculating server due to: An error occurred while sending the request. at [2025-04-14 19:56:01.267]
[INFO] Central web server started at [2025-04-14 19:56:20.283]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-14 19:56:20.904]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-14 19:56:46.534]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 19:56:46.593]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 19:56:46.595]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-14 19:56:46.600]
[INFO] Made request to crack password using brute force method at [2025-04-14 19:56:50.310]
[INFO] {"userLogin":"user1","passwordLength":8} at [2025-04-14 19:56:50.312]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 19:56:50.324]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 19:56:50.325]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-14 19:58:33.958]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 19:58:34.004]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 19:58:34.006]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-14 19:58:34.007]
[INFO] Made request to crack password using brute force method at [2025-04-14 19:58:35.085]
[INFO] {"userLogin":"user1","passwordLength":8} at [2025-04-14 19:58:35.086]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 19:58:35.096]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 19:58:35.098]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 19:58:35.160]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 19:58:35.161]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-14 19:58:57.483]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 19:58:57.528]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 19:58:57.530]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-14 19:58:57.531]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-14 19:59:48.271]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 19:59:48.316]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 19:59:48.318]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-14 19:59:48.319]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-14 20:06:22.928]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:06:22.975]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:06:22.976]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-14 20:06:22.977]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-14 20:06:32.905]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:06:32.950]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:06:32.951]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-14 20:06:32.952]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-14 20:06:44.434]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:06:44.479]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:06:44.481]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-14 20:06:44.482]
[INFO] Central web server started at [2025-04-14 20:07:25.481]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-14 20:07:26.078]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-14 20:07:26.902]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:07:26.961]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:07:26.962]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-14 20:07:26.968]
[INFO] Made request to crack password using brute force method at [2025-04-14 20:07:35.301]
[INFO] {"userLogin":"user1","passwordLength":8} at [2025-04-14 20:07:35.303]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:07:35.315]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:07:35.316]
[INFO] Made request to crack password using brute force method at [2025-04-14 20:08:03.202]
[INFO] {"userLogin":"user1","passwordLength":8} at [2025-04-14 20:08:03.203]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:08:03.214]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:08:03.215]
[INFO] Made request to crack password using brute force method at [2025-04-14 20:13:17.484]
[INFO] {"userLogin":"user1","passwordLength":8} at [2025-04-14 20:13:17.486]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:13:17.496]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:13:17.497]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-14 20:15:31.265]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:15:31.310]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:15:31.311]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-14 20:15:31.313]
[INFO] Made request to crack password using brute force method at [2025-04-14 20:15:32.289]
[INFO] {"userLogin":"user1","passwordLength":8} at [2025-04-14 20:15:32.291]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:15:32.304]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:15:32.305]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:15:32.387]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:15:32.388]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-14 20:16:45.878]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:16:45.924]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:16:45.925]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-14 20:16:45.926]
[INFO] Made request to crack password using brute force method at [2025-04-14 20:16:46.640]
[INFO] {"userLogin":"user1","passwordLength":8} at [2025-04-14 20:16:46.641]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:16:46.652]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:16:46.653]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:16:46.716]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:16:46.717]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:16:46.757]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:16:46.758]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-14 20:17:59.397]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:17:59.453]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:17:59.454]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-14 20:17:59.456]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-14 20:18:37.075]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:18:37.120]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:18:37.122]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-14 20:18:37.123]
[INFO] Made request to crack password using brute force method at [2025-04-14 20:18:40.275]
[INFO] {"userLogin":"user1","passwordLength":8} at [2025-04-14 20:18:40.278]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:18:40.289]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:18:40.290]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:18:40.362]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:18:40.364]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:18:40.405]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:18:40.406]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:18:40.442]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:18:40.443]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:18:40.480]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:18:40.482]
[INFO] Made request to crack password using brute force method at [2025-04-14 20:19:25.025]
[INFO] {"userLogin":"user1","passwordLength":8} at [2025-04-14 20:19:25.027]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:19:25.036]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:19:25.037]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:19:25.081]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:19:25.082]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:19:25.121]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:19:25.122]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:19:25.156]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:19:25.158]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:19:25.194]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:19:25.195]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-14 20:20:51.717]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:20:51.763]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:20:51.765]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-14 20:20:51.766]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-14 20:21:32.845]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:21:32.891]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:21:32.892]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-14 20:21:32.893]
[INFO] Made request to crack password using brute force method at [2025-04-14 20:21:36.914]
[INFO] {"userLogin":"user1","passwordLength":8} at [2025-04-14 20:21:36.915]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:21:36.928]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:21:36.929]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:21:37.013]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:21:37.014]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:21:37.053]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:21:37.055]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:21:37.091]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:21:37.092]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:21:37.134]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:21:37.136]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:21:37.170]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:21:37.172]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:21:37.207]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:21:37.208]
[INFO] Central web server started at [2025-04-14 20:30:38.816]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-14 20:30:39.363]
[INFO] Made request to crack password using brute force method at [2025-04-14 20:30:42.289]
[INFO] {"userLogin":"user1","passwordLength":8} at [2025-04-14 20:30:42.291]
[ERROR] Cannot connect to calculating server due to: Attempted to divide by zero. at [2025-04-14 20:30:42.293]
[INFO] Central web server started at [2025-04-14 20:31:03.938]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-14 20:31:04.379]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-14 20:31:13.729]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:31:13.788]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:31:13.789]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-14 20:31:13.794]
[INFO] Made request to crack password using brute force method at [2025-04-14 20:31:18.954]
[INFO] {"userLogin":"user1","passwordLength":6} at [2025-04-14 20:31:18.956]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:31:18.967]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:31:18.968]
[INFO] Made request to crack password using brute force method at [2025-04-14 20:31:30.917]
[INFO] {"userLogin":"user1","passwordLength":6} at [2025-04-14 20:31:30.919]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:31:30.929]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:31:30.930]
[INFO] Made request to crack password using brute force method at [2025-04-14 20:31:42.798]
[INFO] {"userLogin":"user1","passwordLength":6} at [2025-04-14 20:31:42.800]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:31:42.809]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:31:42.810]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-14 20:32:48.865]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:32:48.912]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:32:48.915]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-14 20:32:48.916]
[INFO] Central web server started at [2025-04-14 20:33:02.666]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-14 20:33:03.206]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-14 20:33:08.851]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:33:08.913]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:33:08.914]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-14 20:33:08.919]
[INFO] Made request to crack password using brute force method at [2025-04-14 20:33:38.441]
[INFO] {"userLogin":"user1","passwordLength":8} at [2025-04-14 20:33:38.442]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:33:38.456]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:33:38.458]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-14 20:34:12.360]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:34:12.404]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:34:12.405]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-14 20:34:12.406]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-14 20:34:21.929]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:34:21.975]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:34:21.976]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-14 20:34:21.977]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-14 20:34:56.993]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:34:57.038]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:34:57.039]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-14 20:34:57.041]
[INFO] Central web server started at [2025-04-14 20:36:58.265]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-14 20:36:58.888]
[INFO] Central web server started at [2025-04-14 20:37:11.766]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-14 20:37:12.252]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-14 20:37:14.122]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:37:14.180]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:37:14.181]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-14 20:37:14.187]
[INFO] Made request to crack password using brute force method at [2025-04-14 20:37:24.732]
[INFO] {"userLogin":"user1","passwordLength":8} at [2025-04-14 20:37:24.734]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:37:24.746]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:37:24.748]
[ERROR] Cannot connect to calculating server due to: 'S' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0. at [2025-04-14 20:37:24.840]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-14 20:37:55.327]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:37:55.372]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:37:55.374]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-14 20:37:55.375]
[INFO] Made request to crack password using brute force method at [2025-04-14 20:37:59.956]
[INFO] {"userLogin":"user1","passwordLength":8} at [2025-04-14 20:37:59.969]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:37:59.991]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:38:00.003]
[ERROR] Cannot connect to calculating server due to: 'S' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0. at [2025-04-14 20:38:00.088]
[INFO] Central web server started at [2025-04-14 20:38:18.304]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-14 20:38:18.949]
[INFO] Made request to crack password using brute force method at [2025-04-14 20:38:23.950]
[INFO] {"userLogin":"user1","passwordLength":8} at [2025-04-14 20:38:23.952]
[ERROR] Cannot connect to calculating server due to: Attempted to divide by zero. at [2025-04-14 20:38:23.954]
[INFO] Central web server started at [2025-04-14 20:38:43.531]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-14 20:38:43.996]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.52 at [2025-04-14 20:38:44.550]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:38:44.611]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:38:44.613]
[INFO] Calculating server with IP address: 192.168.0.52 successfully connected to the central server at [2025-04-14 20:38:44.618]
[INFO] Made request to crack password using brute force method at [2025-04-14 20:38:51.975]
[INFO] {"userLogin":"user1","passwordLength":8} at [2025-04-14 20:38:51.977]
[INFO] Dictionary already exists on server 192.168.0.52 at path: /App/dictionary/dictionary-F3924E4A20B2A32A-2025-04-12.txt at [2025-04-14 20:38:51.988]
[INFO] Successfully connected to calculating server 192.168.0.52 at [2025-04-14 20:38:51.989]
